In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("season_batting_card.csv")

In [10]:
df.shape

(919, 25)

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 919 entries, 0 to 918
Data columns (total 25 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   season           919 non-null    float64
 1   match_id         919 non-null    int64
 2   match_name       919 non-null    object
 3   home_team        919 non-null    object
 4   away_team        919 non-null    object
 5   venue            919 non-null    object
 6   city             919 non-null    object
 7   country          919 non-null    object
 8   current_innings  919 non-null    object
 9   innings_id       919 non-null    int64
 10  name             919 non-null    object
 11  fullName         919 non-null    object
 12  runs             919 non-null    int64
 13  ballsFaced       919 non-null    int64
 14  minutes          919 non-null    object
 15  fours            919 non-null    int64
 16  sixes            919 non-null    int64
 17  strikeRate       919 non-null    object
 18  captain          919 non-null    bool
 19  isNotOut         919 non-null    bool
 20  runningScore     919 non-null    object
 21  runningOver      705 non-null    float64
 22  shortText        919 non-null    object
 23  commentary       705 non-null    object
 24  link             0 non-null      float64
dtypes: bool(2), float64(3), int64(6), object(14)
memory usage: 167.1+ KB

In [13]:
df.corr()

,season,match_id,innings_id,runs,ballsFaced,fours,sixes,captain,isNotOut,runningOver,link
season,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
match_id,NaN,1.000000,-0.002587,-0.036003,0.004110,-0.066425,-0.062878,0.008734,0.016726,-0.026881,NaN
innings_id,NaN,-0.002587,1.000000,0.036305,0.028889,0.049325,0.020801,0.020768,0.066403,-0.087194,NaN
runs,NaN,-0.036003,0.036305,1.000000,0.934565,0.880518,0.793107,0.152058,0.036995,0.170310,NaN
ballsFaced,NaN,0.004110,0.028889,0.934565,1.000000,0.796551,0.637772,0.186271,-0.040439,0.150956,NaN
fours,NaN,-0.066425,0.049325,0.880518,0.796551,1.000000,0.530644,0.136440,-0.012306,0.050087,NaN
sixes,NaN,-0.062878,0.020801,0.793107,0.637772,0.530644,1.000000,0.056627,0.078923,0.162491,NaN
captain,NaN,0.008734,0.020768,0.152058,0.186271,0.136440,0.056627,1.000000,-0.041656,-0.100387,NaN
isNotOut,NaN,0.016726,0.066403,0.036995,-0.040439,-0.012306,0.078923,-0.041656,1.000000,NaN,NaN
runningOver,NaN,-0.026881,-0.087194,0.170310,0.150956,0.050087,0.162491,-0.100387,NaN,1.000000,NaN
link,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
df.sample(n=10)

,season,match_id,match_name,home_team,away_team,venue,city,country,current_innings,innings_id,...,fours,sixes,strikeRate,captain,isNotOut,runningScore,runningOver,shortText,commentary,link
822,2021.0,1254063,SRH v RCB,SRH,RCB,"MA Chidambaram Stadium, Chepauk, Chennai",Chennai,India,RCB,1,...,1,0,72.72,False,False,"{'wickets': 5, 'runs': 105}",15.5,c Pandey b Rashid Khan,"Pandey runs in from long-off, dives forward, a...",NaN
617,2021.0,1254076,CSK v RCB,CSK,RCB,"Wankhede Stadium, Mumbai",Mumbai,India,RCB,2,...,4,2,226.66,False,False,"{'wickets': 2, 'runs': 54}",4.6,c Raina b Thakur,<b>taken at backward square!</b> The bowling c...,NaN
327,2021.0,1254108,RCB v MI,RCB,MI,Dubai International Cricket Stadium,Dubai,United Arab Emirates,MI,2,...,1,0,83.33,False,False,"{'wickets': 9, 'runs': 111}",17.3,b Chahal,<strong>cleans him up!</strong> The off stump ...,NaN
285,2021.0,1254092,KKR v DC,KKR,DC,Sharjah Cricket Stadium,Sharjah,United Arab Emirates,DC,1,...,0,0,0.00,False,False,"{'wickets': 6, 'runs': 92}",15.3,c Ferguson b Iyer,full on middle and leg. <B>Clipped</b> but Loc...,NaN
380,2021.0,1254097,DC v RR,DC,RR,"Sheikh Zayed Stadium, Abu Dhabi",Abu Dhabi,United Arab Emirates,RR,2,...,0,0,50.00,False,True,{},NaN,not out,NaN,NaN
912,2021.0,1254058,MI v RCB,MI,RCB,"MA Chidambaram Stadium, Chepauk, Chennai",Chennai,India,RCB,2,...,3,2,139.28,False,False,"{'wickets': 4, 'runs': 103}",14.1,c Lynn b Jansen,<b>ramped straight to short fine!</b> It's a s...,NaN
343,2021.0,1254098,CSK v KKR,CSK,KKR,"Sheikh Zayed Stadium, Abu Dhabi",Abu Dhabi,United Arab Emirates,CSK,2,...,2,2,275.00,False,False,"{'wickets': 8, 'runs': 171}",19.5,lbw b Narine,"straighter ball, and he looks to sweep this. <...",NaN
381,2021.0,1254113,RCB v CSK,RCB,CSK,Sharjah Cricket Stadium,Sharjah,United Arab Emirates,RCB,1,...,6,1,129.26,True,False,"{'wickets': 1, 'runs': 111}",13.2,c Jadeja b Bravo,<B>short-arm jab straight to deep midwicket!</...,NaN
667,2021.0,1254072,KKR v CSK,KKR,CSK,"Wankhede Stadium, Mumbai",Mumbai,India,CSK,1,...,6,4,152.38,False,False,"{'wickets': 1, 'runs': 115}",12.2,c Cummins b Varun,"<strong>hauled to deep midwicket, where Cummin...",NaN
129,2021.0,1254093,RR v MI,RR,MI,Sharjah Cricket Stadium,Sharjah,United Arab Emirates,RR,1,...,0,0,50.00,True,False,"{'wickets': 3, 'runs': 41}",6.1,c J Yadav b Neesham,<B>Neesham strikes first ball!</b> How about t...,NaN

In [17]:
df.columns

Index(['season', 'match_id', 'match_name', 'home_team', 'away_team', 'venue',
       'city', 'country', 'current_innings', 'innings_id', 'name', 'fullName',
       'runs', 'ballsFaced', 'minutes', 'fours', 'sixes', 'strikeRate',
       'captain', 'isNotOut', 'runningScore', 'runningOver', 'shortText',
       'commentary', 'link'],
      dtype='object')

In [26]:
print(df['home_team'].nunique(),df['away_team'].nunique(),df['venue'].nunique(), df['country'].nunique(), df['match_name'].nunique())

8 8 7 2 56

In [28]:
df.nlargest(10, 'runs')

,season,match_id,match_name,home_team,away_team,venue,city,country,current_innings,innings_id,...,fours,sixes,strikeRate,captain,isNotOut,runningScore,runningOver,shortText,commentary,link
484,2021.0,1254085,RR v SRH,RR,SRH,"Arun Jaitley Stadium, Delhi",Delhi,India,RR,1,...,11,8,193.75,False,False,"{'wickets': 3, 'runs': 209}",18.6,b Sandeep Sharma,"fullish and outside off, Buttler has a slog at...",NaN
866,2021.0,1254061,RR v PBKS,RR,PBKS,"Wankhede Stadium, Mumbai",Mumbai,India,RR,2,...,12,7,188.88,True,False,"{'wickets': 7, 'runs': 217}",19.6,c Hooda b Arshdeep Singh,Samson can't clear deep cover. The nerveless <...,NaN
191,2021.0,1254089,RR v CSK,RR,CSK,"Sheikh Zayed Stadium, Abu Dhabi",Abu Dhabi,United Arab Emirates,CSK,1,...,9,5,168.33,False,True,{},NaN,not out,NaN,NaN
666,2021.0,1254073,RCB v RR,RCB,RR,"Wankhede Stadium, Mumbai",Mumbai,India,RCB,2,...,11,6,194.23,False,True,{},NaN,not out,NaN,NaN
472,2021.0,1254086,PBKS v DC,PBKS,DC,"Narendra Modi Stadium, Motera, Ahmedabad",Ahmedabad,India,PBKS,1,...,8,4,170.68,True,True,{},NaN,not out,NaN,NaN
105,2021.0,1254094,CSK v PBKS,CSK,PBKS,Dubai International Cricket Stadium,Dubai,United Arab Emirates,PBKS,2,...,7,8,233.33,True,True,{},NaN,not out,NaN,NaN
668,2021.0,1254072,KKR v CSK,KKR,CSK,"Wankhede Stadium, Mumbai",Mumbai,India,CSK,1,...,9,4,158.33,False,True,{},NaN,not out,NaN,NaN
743,2021.0,1254068,DC v PBKS,DC,PBKS,"Wankhede Stadium, Mumbai",Mumbai,India,DC,2,...,13,2,187.75,False,False,"{'wickets': 3, 'runs': 152}",14.5,b Richardson,<b>splits middle and off stump!</b> Jhye pumps...,NaN
513,2021.0,1254083,PBKS v RCB,PBKS,RCB,"Narendra Modi Stadium, Motera, Ahmedabad",Ahmedabad,India,PBKS,1,...,7,5,159.64,True,True,{},NaN,not out,NaN,NaN
857,2021.0,1254061,RR v PBKS,RR,PBKS,"Wankhede Stadium, Mumbai",Mumbai,India,PBKS,1,...,7,5,182.00,True,False,"{'wickets': 5, 'runs': 220}",19.2,c Tewatia b Sakariya,"full and in the slot around off stump, Rahul p...",NaN

In [29]:
df.isnull().sum()

season               0
match_id             0
match_name           0
home_team            0
away_team            0
venue                0
city                 0
country              0
current_innings      0
innings_id           0
name                 0
fullName             0
runs                 0
ballsFaced           0
minutes              0
fours                0
sixes                0
strikeRate           0
captain              0
isNotOut             0
runningScore         0
runningOver        214
shortText            0
commentary         214
link               919
dtype: int64

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 919 entries, 0 to 918
Data columns (total 25 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   season           919 non-null    float64
 1   match_id         919 non-null    int64
 2   match_name       919 non-null    object
 3   home_team        919 non-null    object
 4   away_team        919 non-null    object
 5   venue            919 non-null    object
 6   city             919 non-null    object
 7   country          919 non-null    object
 8   current_innings  919 non-null    object
 9   innings_id       919 non-null    int64
 10  name             919 non-null    object
 11  fullName         919 non-null    object
 12  runs             919 non-null    int64
 13  ballsFaced       919 non-null    int64
 14  minutes          919 non-null    object
 15  fours            919 non-null    int64
 16  sixes            919 non-null    int64
 17  strikeRate       919 non-null    object
 18  captain          919 non-null    bool
 19  isNotOut         919 non-null    bool
 20  runningScore     919 non-null    object
 21  runningOver      705 non-null    float64
 22  shortText        919 non-null    object
 23  commentary       705 non-null    object
 24  link             0 non-null      float64
dtypes: bool(2), float64(3), int64(6), object(14)
memory usage: 167.1+ KB

In [ ]:
data = df[['season', 'match_id', 'match_name', 'home_team', 'away_team', 'venue',
       'city', 'country', 'current_innings', 'innings_id', 'name', 'fullName',
       'runs', 'ballsFaced', 'minutes', 'fours', 'sixes', 'strikeRate',
       'captain', 'isNotOut', 'runningScore', 'shortText',
       ]]